user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

site_plaque:
    resource: "@SitePlaqueBundle/Controller/"
    type:     annotation
    prefix:   /

home:
    path: /home
    defaults: { _controller: SitePlaqueBundle:Home:index }

login:
    path: /login
    defaults:  { _controller: UserBundle:Security:login }

login_check:
    path: /login_check

register:
    path: /register
    defaults:  { _controller: SitePlaqueBundle:Client:add }