user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

site_plaque:
    resource: "@SitePlaqueBundle/Controller/"
    type:     annotation
    prefix:   /

accueil_platform:
    path: /accueil
    defaults: { _controller: SitePlaqueBundle:Accueil:index }

plaque_platform:
    path: /plaques
    defaults: { _controller: SitePlaqueBundle:Plaque:index}

plaque_single:
    path:      /plaques/maplaque/{id}
    defaults:  { _controller: SitePlaqueBundle:Plaque:single }
    requirements:
        id: \d*

plaque_edit:
    path:       /plaques/edit/{id}
    defaults:   {_controller: SitePlaqueBundle:Plaque:edit }
    requirements:
        id: \d*

plaque_creation:
    path:     /plaques/ajout
    defaults: {_controller: SitePlaqueBundle:Plaque:add }

plaque_succes:
    path:     /plaques/ajoutvalide
    defaults: {_controller: SitePlaqueBundle:Plaque:succes }

plaque_supprime:
    path:     /plaques/supprimer/{id}
    defaults: {_controller: SitePlaqueBundle:Plaque:delete }
    requirements:
        id: \d*

plaque_supprime_valide:
    path:     /plaques/suppressionvalide
    defaults: {_controller: SitePlaqueBundle:Plaque:deletevalide }

devis_platform:
    path:      /devis
    defaults: { _controller: SitePlaqueBundle:Devis:index }

devis_view:
    path:      /devis/mondevis/{id}
    defaults:  { _controller: SitePlaqueBundle:Devis:view }
    requirements:
        id: \d*

devis_ajout:
    path:      /devis/ajout/{id}
    defaults: {_controller: SitePlaqueBundle:Devis:add}

devis_supprime:
    path:     /devis/suppression/{id}
    defaults: { _controller: SitePlaqueBundle:Devis:delete }
    requirements:
        id: \d*

devis_supprime_valide:
    path:     /devis/suppressionvalide
    defaults: { _controller: SitePlaqueBundle:Devis:deletevalide }

devis_all_plaques:
    path: /devis/ajout/totalite/plaques
    defaults: { _controller: SitePlaqueBundle:Devis:addAll }
    
admin_listeUser:
    path: /admin/listeClient
    defaults: { _controller: SitePlaqueBundle:Admin:listUser }

admin_listedevis:
    path: /admin/listeDevis
    defaults: { _controller: SitePlaqueBundle:Admin:listDevis }

admin_oneuser:
    path: /admin/ListeClient/Client/{id}
    defaults: { _controller: UserBundle:Utilisateur:client }
    requirements:
        id: \d*

admin_warning:
    path: /admin/utilisateur/suppression
    defaults: { _controller: UserBundle:Utilisateur:warningAdmin }

admin_supprim_client:
    path: /admin/suppression/Devis/{id}
    defaults: { _controller: UserBundle:Utilisateur:deleteClient }
    requirements:
        id: \d*

admin_prix_list:
    path: /admin/prixunitaires
    defaults: { _controller: SitePlaqueBundle:PrixUnitaire:list }

admin_prix_edit:
    path: /admin/prixunitaires/edit/{id}
    defaults: { _controller: SitePlaqueBundle:PrixUnitaire:edit }
    requirements:
        id: \d*

prix_success:
    path: /admin/prixunitaires/modificationValide
    defaults: { _controller: SitePlaqueBundle:PrixUnitaire:succes }

user_warning:
    path: /utilisateur/suppression
    defaults: { _controller:UserBundle:Utilisateur:warning }

user_delete:
    path: /utilisateur/suppression/valider
    defaults: { _controller:UserBundle:Utilisateur:delete }

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_resetting_request:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"





   

