# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
        encoders: 
                Symfony\Component\Security\Core\User\User: plaintext
                UserBundle\Entity\Utilisateur: sha512
        role_hierarchy:
                   ROLE_ADMIN: ROLE_USER
                   ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]				   


        providers:
            main:
                id: fos_user.user_provider.username

        firewalls:
            dev:
                pattern: ^/(_(profiler|wdt)|css|images|js)/
                security: false
            main:
                pattern: ^/
                anonymous: true
                provider: main
                form_login:
                   login_path: fos_user_security_login
                   check_path: fos_user_security_check
                   always_use_default_target_path : true
                   default_target_path: /accueil
                   use_referer : true				   
                logout:
                   path: fos_user_security_logout
                   target: /accueil
                remember_me:
                    key: %secret% 

        access_control: 
                - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
                - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
                - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
                - { path: ^/devis, roles: ROLE_USER }
                - { path: ^/admin, role: ROLE_ADMIN }

            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
