services:
      site.form.registration:
          class: UserBundle\Form\RegisterType
          tags: 
               - { name: form.type, alias: site_user_registration }
      site.form.edition:
           class: UserBundle\Form\EditType
           tags: 
               - { name: form.type, alias: site_user_edition }

      #site.form.plaque:
          #class: SitePlaqueBundle\Form\PlaqueType
          #arguments:
              #- '%plaques%'
          #tags:
              #- { name: form.type }